services:
  db:
    image: postgres:latest
    container_name: meu-atelie
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'ddh'
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
        reservations:
          cpus: '2'
          memory: 1GB
    volumes:
      - ddh-postgres:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  ddh-postgres:
